name: CI

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 * * 0'

jobs:
  Distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [node, alpine, archlinux, centos, debian, fedora, opensuse, ubuntu]
      fail-fast: false
    env:
      DISTRO: ${{ matrix.distro }}
    steps:
    - uses: actions/checkout@v4
    - name: Build env image
      run: make --directory=ci ${DISTRO}_env
    - name: Build devel project
      run: make --directory=ci ${DISTRO}_devel
    - name: Build project
      run: make --directory=ci ${DISTRO}_build
    - name: Test project
      run: make --directory=ci ${DISTRO}_test
